name: weather
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  connectivity_plus: ^4.0.1
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.8.0
  flutter_svg: ^2.0.7
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  go_router: ^9.0.0
  google_fonts: ^5.0.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  jiffy: ^6.2.1
  line_icons: ^2.0.1
  logger: ^1.4.0
  lottie: ^2.4.0
  provider: ^6.0.5
  shared_preferences: ^2.1.2
  weather_icons: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # generate: true
  uses-material-design: true
  assets:
    - images/
    - lang/
